services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: car_db
    healthcheck:
      test: "pg_isready -U admin -d admin"
      interval: "10s"
      timeout: "5s"
      retries: 5

    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432
    networks:
      - app_network
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: sahandahmadipgr2004@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "8090:80"
    networks:
      - app_network
    depends_on:
      - postgres

  redis:
    image: redis:latest
    container_name: redis_container
    restart: unless-stopped
    environment:
      REDIS_PASSWORD: admin
    volumes:
      - redis:/data
    ports:
      - "6379:6379"
    networks:
    - app_network
    
volumes:
  pgadmin:
  postgres:
  redis:
  logs:

networks:
  app_network:
    driver: bridge