server:
  port: 8080
  runMode: debug

log:
  path: logs/logs.log
  encoding: json
  level: debug
  logger: zerolog
cors:
  allowOrigins: "*"

postgres:
  host: postgres_container
  port: 5432
  user: postgres
  password: admin
  dbName: car_db
  sslMode: disable
  setMaxIdleConns: 10
  setMaxOpenConns: 100
  setConnMaxLifetime: 5

redis:
  host: localhost
  port: 6379
  password: admin
  db: 0
  idleCheckFrequency: 300
  writeTimeout: 10
  readTimeout: 10
  dialTimeout : 10
  poolSize: 10
  poolTimeout: 30

otp:
  expireTime: 120
  digits: 6
  limiter: 100