server:
  port: 8080
  RunMode: debug

logger:
  filePath: ../logs/logs.log
  Encoding: json
  level: debug

cors:
  allowOrigins: "*"

postgres:
  host: postgres_container
  port: 5432
  user: postgres
  password: admin
  dbName: car_db
  sslMode: false

redis:
  host: localhost
  port: 6379
  password: admin
  db: 0
  idleCheckFrequency: 300
  writeTimeout: 10
  readTimeout: 10
  dialTimeout : 10
  poolSize: 10
  poolTimeout: 30