definitions:
  github_com_sahandPgr_car-selling-service_api_dto.CountryResponse:
    properties:
      id:
        type: integer
      name:
        type: string
    type: object
  github_com_sahandPgr_car-selling-service_api_dto.CreateUpdateCountryRequest:
    properties:
      name:
        maxLength: 20
        minLength: 3
        type: string
    required:
    - name
    type: object
  github_com_sahandPgr_car-selling-service_api_dto.GetOtpRequest:
    properties:
      mobileNumber:
        maxLength: 11
        minLength: 11
        type: string
    required:
    - mobileNumber
    type: object
  github_com_sahandPgr_car-selling-service_api_dto.LoginByUsernameRequest:
    properties:
      password:
        minLength: 4
        type: string
      username:
        minLength: 5
        type: string
    required:
    - password
    - username
    type: object
  github_com_sahandPgr_car-selling-service_api_dto.RegisterLoginByMobileRequest:
    properties:
      otp:
        maxLength: 6
        minLength: 6
        type: string
      phoneMobile:
        maxLength: 11
        minLength: 11
        type: string
    required:
    - otp
    - phoneMobile
    type: object
  github_com_sahandPgr_car-selling-service_api_dto.RegisterUserByUsernameRequest:
    properties:
      email:
        minLength: 6
        type: string
      'firstName:':
        minLength: 3
        type: string
      'lastName:':
        minLength: 6
        type: string
      password:
        minLength: 6
        type: string
      username:
        minLength: 5
        type: string
    required:
    - 'firstName:'
    - 'lastName:'
    - password
    - username
    type: object
  github_com_sahandPgr_car-selling-service_api_helper.BaseHttpResponse:
    properties:
      error: {}
      result: {}
      'statusCode:':
        type: integer
      success:
        type: boolean
      validationErrors:
        items:
          $ref: '#/definitions/github_com_sahandPgr_car-selling-service_api_validations.ValidationError'
        type: array
    type: object
  github_com_sahandPgr_car-selling-service_api_validations.ValidationError:
    properties:
      field:
        type: string
      message:
        type: string
      param:
        type: string
      tag:
        type: string
      value:
        type: string
    type: object
info:
  contact: {}
paths:
  /v1/countries/:
    post:
      consumes:
      - application/json
      description: Create a country
      parameters:
      - description: Create a country
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/github_com_sahandPgr_car-selling-service_api_dto.CreateUpdateCountryRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            allOf:
            - $ref: '#/definitions/github_com_sahandPgr_car-selling-service_api_helper.BaseHttpResponse'
            - properties:
                result:
                  $ref: '#/definitions/github_com_sahandPgr_car-selling-service_api_dto.CountryResponse'
              type: object
        "400":
          description: Failed
          schema:
            $ref: '#/definitions/github_com_sahandPgr_car-selling-service_api_helper.BaseHttpResponse'
        "409":
          description: Failed
          schema:
            $ref: '#/definitions/github_com_sahandPgr_car-selling-service_api_helper.BaseHttpResponse'
      security:
      - AuthBearer: []
      summary: Create a country
      tags:
      - Countries
  /v1/countries/{id}:
    delete:
      consumes:
      - application/json
      description: Delete a country
      parameters:
      - description: Delete a country
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            $ref: '#/definitions/github_com_sahandPgr_car-selling-service_api_helper.BaseHttpResponse'
        "400":
          description: Failed
          schema:
            $ref: '#/definitions/github_com_sahandPgr_car-selling-service_api_helper.BaseHttpResponse'
        "409":
          description: Failed
          schema:
            $ref: '#/definitions/github_com_sahandPgr_car-selling-service_api_helper.BaseHttpResponse'
      security:
      - AuthBearer: []
      summary: Delete a country
      tags:
      - Countries
    get:
      consumes:
      - application/json
      description: Get a country
      parameters:
      - description: Get a country
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            allOf:
            - $ref: '#/definitions/github_com_sahandPgr_car-selling-service_api_helper.BaseHttpResponse'
            - properties:
                result:
                  $ref: '#/definitions/github_com_sahandPgr_car-selling-service_api_dto.CountryResponse'
              type: object
        "400":
          description: Failed
          schema:
            $ref: '#/definitions/github_com_sahandPgr_car-selling-service_api_helper.BaseHttpResponse'
        "409":
          description: Failed
          schema:
            $ref: '#/definitions/github_com_sahandPgr_car-selling-service_api_helper.BaseHttpResponse'
      security:
      - AuthBearer: []
      summary: Get a country
      tags:
      - Countries
    put:
      consumes:
      - application/json
      description: Update a country
      parameters:
      - description: Update a country
        in: path
        name: id
        required: true
        type: integer
      - description: Update a country
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/github_com_sahandPgr_car-selling-service_api_dto.CreateUpdateCountryRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            allOf:
            - $ref: '#/definitions/github_com_sahandPgr_car-selling-service_api_helper.BaseHttpResponse'
            - properties:
                result:
                  $ref: '#/definitions/github_com_sahandPgr_car-selling-service_api_dto.CountryResponse'
              type: object
        "400":
          description: Failed
          schema:
            $ref: '#/definitions/github_com_sahandPgr_car-selling-service_api_helper.BaseHttpResponse'
        "409":
          description: Failed
          schema:
            $ref: '#/definitions/github_com_sahandPgr_car-selling-service_api_helper.BaseHttpResponse'
      security:
      - AuthBearer: []
      summary: Update a country
      tags:
      - Countries
  /v1/user/login-by-username:
    post:
      consumes:
      - application/json
      description: LoginByUsername
      parameters:
      - description: LoginByUsernameRequest
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/github_com_sahandPgr_car-selling-service_api_dto.LoginByUsernameRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            $ref: '#/definitions/github_com_sahandPgr_car-selling-service_api_helper.BaseHttpResponse'
        "400":
          description: Failed
          schema:
            $ref: '#/definitions/github_com_sahandPgr_car-selling-service_api_helper.BaseHttpResponse'
        "409":
          description: Failed
          schema:
            $ref: '#/definitions/github_com_sahandPgr_car-selling-service_api_helper.BaseHttpResponse'
      summary: LoginByUsername
      tags:
      - Users
  /v1/user/register-by-username:
    post:
      consumes:
      - application/json
      description: RegisterByUsername
      parameters:
      - description: RegisterUserByUsernameRequest
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/github_com_sahandPgr_car-selling-service_api_dto.RegisterUserByUsernameRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            $ref: '#/definitions/github_com_sahandPgr_car-selling-service_api_helper.BaseHttpResponse'
        "400":
          description: Failed
          schema:
            $ref: '#/definitions/github_com_sahandPgr_car-selling-service_api_helper.BaseHttpResponse'
        "409":
          description: Failed
          schema:
            $ref: '#/definitions/github_com_sahandPgr_car-selling-service_api_helper.BaseHttpResponse'
      summary: RegisterByUsername
      tags:
      - Users
  /v1/user/register-login-by-phone:
    post:
      consumes:
      - application/json
      description: RegisterLoginByMobile
      parameters:
      - description: RegisterLoginByMobileRequest
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/github_com_sahandPgr_car-selling-service_api_dto.RegisterLoginByMobileRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            $ref: '#/definitions/github_com_sahandPgr_car-selling-service_api_helper.BaseHttpResponse'
        "400":
          description: Failed
          schema:
            $ref: '#/definitions/github_com_sahandPgr_car-selling-service_api_helper.BaseHttpResponse'
        "409":
          description: Failed
          schema:
            $ref: '#/definitions/github_com_sahandPgr_car-selling-service_api_helper.BaseHttpResponse'
      summary: RegisterLoginByMobile
      tags:
      - Users
  /v1/user/send-otp:
    post:
      consumes:
      - application/json
      description: Send otp
      parameters:
      - description: GetOtpRequest
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/github_com_sahandPgr_car-selling-service_api_dto.GetOtpRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            $ref: '#/definitions/github_com_sahandPgr_car-selling-service_api_helper.BaseHttpResponse'
        "400":
          description: Failed
          schema:
            $ref: '#/definitions/github_com_sahandPgr_car-selling-service_api_helper.BaseHttpResponse'
        "409":
          description: Failed
          schema:
            $ref: '#/definitions/github_com_sahandPgr_car-selling-service_api_helper.BaseHttpResponse'
      summary: Send otp
      tags:
      - Users
securityDefinitions:
  AuthBearer:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
